### PR TITLE
Use routing info bbs endpoint when syncing

### PR DESCRIPTION
**Pull request by klapkov**
This PR is related to this issue: https://github.com/cloudfoundry/diego-release/issues/678. Here we change the bbs endpoint used to retrieve the desiredLRP's when syncing. We receive a desiredLRP structure with only the needed information for the route emitter.

### CODE REVIEW

**Comment by klapkov** [comment]
Related PR in the BBS: https://github.com/cloudfoundry/bbs/pull/66

**Comment by PlamenDoychev** [comment]
Looks good to me @geofffranks what do you think?

**Comment by klapkov** [comment]
@geofffranks The bbs fake client was already updated, now I updated all the watcher tests and added a new case for when retrieving the desiredLRP's and we need to fallback to the old route.

**Review by geofffranks — APPROVED** [review]

**Comment by geofffranks** [comment]
LGTM - let's see what CI says

**Pull request merged**
